services:
    access.user_provider:
        class: AccessBundle\UserProvider
        arguments: [@doctrine_mongodb]
        tags:
            - {name: json_rpc.service, method: loadUserByUsername} 
    access: @access.user_provider
    access.user:
        class: AccessBundle\UserService
        arguments: [@doctrine_mongodb]
    access.api_voter:
        class:      AccessBundle\ApiVoter
        public:     false
        tags:
           - { name: security.voter }