imports:
    - { resource: listeners.yml }
    - { resource: events.xml }
    - { resource: email_providers.yml }

services:
    app.doctrine_aware:
        class: AppBundle\Service\AbstractDoctrineAware
        arguments: [@doctrine, @logger, @event_dispatcher]
        abstract: true        
    app.warehouse:
        class: AppBundle\Service\WarehouseService
        parent: app.doctrine_aware
        tags:
            - {name: json_rpc.service, method: getAll} 
        calls:
            - ["setUtilService", [@app.util]] 
    app.catalog:
        class: AppBundle\Service\CatalogService
        parent: app.doctrine_aware 
        tags:
            - {name: json_rpc.service, method: getCategories}
            - {name: json_rpc.service, method: getProductSales}      
    app.order:
        class: AppBundle\Service\OrderService
        parent: app.doctrine_aware
        tags:
            - {name: json_rpc.service, method: createOrder}            
    order: @app.order    
    warehouse: @app.warehouse
    catalog: @app.catalog
    app.email:
        class: AppBundle\Service\Communication\EmailService
        public: false
        arguments: [@app.util, %maximum_emails_per_second%]
        calls:
            - ["addProvider", [@app.provider_email_external]] 
    app.communication:
        class: AppBundle\Service\Communication\CommunicationService
        arguments: [@app.email, @templating, @translator, @event_dispatcher]        
    event_dispatcher:
        class: AppBundle\Event\EventDispatcher
        arguments: [@service_container]        
    app.document:
        class: AppBundle\Service\Document\DocumentService
        arguments: [@templating, @event_dispatcher, @doctrine_mongodb, @old_sound_rabbit_mq.document_producer]
    app.delivery:
        class: AppBundle\Service\DeliveryService
        parent: app.doctrine_aware
    app.util:
        class: AppBundle\Service\UtilService
        arguments: [@doctrine, @logger, @memcached]
    memcached:
        class: Memcached
        calls:
            - [ addServers, [ %memcached.servers% ]]
    app.translator:
        class: AppBundle\Service\Translator
        decorates: translator.default
        arguments: ["@app.translator.inner"]
        public: false